services:
  - type: web
    name: telegram-rss-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python your_script_name.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "your_telegram_bot_token"
      - key: FEED_UPDATE_INTERVAL
        value: "3600"
      - key: EXCLUDE_WORDS
        value: "word1\nword2\nword3"
      - key: ARCHIVE_POSTS
        value: "true"
